### ISSUE TITLE
[eld] and dump each query to separate smt file and then apply eldarica simplification

### ISSUE THREAD

**Issue by izlatkin** [izlatkin/solidity_testgen#18]
example of dump query to smt:
https://github.com/grigoryfedyukovich/aeval/blob/rnd/include/deep/Horn.hpp#L1222
void serialize ()

Research: find slicing options of eldarica

**Comment by izlatkin** [comment]
eldarica command:
`./eld orig_quiry.smt2 -sp`

It seems like after slicing encoding is more compact (50843 chars vs 100205 chars ).

```
cat  after_eld.smt2 | wc -c
   50843
orig_quiry.smt2 | wc -c
  100205
Ilyas-MacBook-Pro:eldr ilyazlatkin$ time z3  ~/CLionProjects/aeval/sandbox/tg_query.smt2
unsat

real	0m0.112s
user	0m0.062s
sys	0m0.022s
Ilyas-MacBook-Pro:eldr ilyazlatkin$ time z3 gen.smt2 
unsat

real	0m0.142s
user	0m0.064s
sys	0m0.026s
```


files:
[orig_quiry.smt2.txt](https://github.com/izlatkin/solidity_testgen/files/9530095/orig_quiry.smt2.txt)
[after_eld.smt2.txt](https://github.com/izlatkin/solidity_testgen/files/9530098/after_eld.smt2.txt)

**Comment by izlatkin** [comment]
but it is not clear how to extract variables from the model. Looks like eldarica rename them. 
For example, for contract
`contract C { function simple_if_u(uint256 xyzpoiqwe) ....`
in the original query, we can find `xyzpoiqwe` but we can not find them after eldarica processing.

Fils attached:
[eld_processing.smt2.txt](https://github.com/izlatkin/solidity_testgen/files/9530764/eld_processing.smt2.txt)
[tg_query.smt2.txt](https://github.com/izlatkin/solidity_testgen/files/9530771/tg_query.smt2.txt)

**Comment by grigoryfedyukovich** [comment]
Some CHC simplifications may remove them. It's hard to figure out now.

**Comment by izlatkin** [comment]
@grigoryfedyukovich could it be that they have been remained?

**Comment by izlatkin** [comment]
done: no profit from this. slicing did not fix the performance issue.
