### ISSUE TITLE
[tg] a few functions are ignored  during test generations

### ISSUE THREAD

**Issue by izlatkin** [izlatkin/solidity_testgen#19]
few functions are ignored, it seems like pretty simple test cases
<img width="792" alt="image" src="https://user-images.githubusercontent.com/16242682/188738215-1aa64128-877e-45c1-9d7a-322945acd969.png">

[many_fun_wo_adt.smt2.txt](https://github.com/izlatkin/solidity_testgen/files/9500731/many_fun_wo_adt.smt2.txt)
[log.txt](https://github.com/izlatkin/solidity_testgen/files/9500733/log.txt)
[many_fun_updated.sol.txt](https://github.com/izlatkin/solidity_testgen/files/9500736/many_fun_updated.sol.txt)

**Comment by izlatkin** [comment]
it seems like the issue related to the function `void mkNewQuery(int cycl_num)`

chcs 
```
0 srs:  dst: 71 : nondet_interface_1_C_61_0 isQuery : 0
1 srs:  71 136 dst: 71 : nondet_interface_1_C_61_0 isQuery : 0
2 srs:  71 151 dst: 71 : nondet_interface_1_C_61_0 isQuery : 0
3 srs:  71 166 dst: 71 : nondet_interface_1_C_61_0 isQuery : 0
4 srs:  71 181 dst: 71 : nondet_interface_1_C_61_0 isQuery : 0
5 srs:  71 196 dst: 71 : nondet_interface_1_C_61_0 isQuery : 0
......
15 srs:  331 326 dst: 136 : summary_4_function_f__14_61_0 isQuery : 0
....
61 srs:  **136** dst: 1119 : error_target_6_0 isQuery : 1 
```

but it supported to be `71` instead of `136`
`61 srs:  **71** dst: 1119 : error_target_6_0 isQuery : 1 `

for current encoding, we generate tests that start with `f1`

**Comment by izlatkin** [comment]
[dots.zip](https://github.com/izlatkin/solidity_testgen/files/9635294/dots.zip)
all trees have "summary_4_function_f1" because we have `136`

**Comment by grigoryfedyukovich** [comment]
As per my understanding, `nondet_interface_1_C_108_0` should not appear in the new query. This is just an interface predicate that we handle externally in `mkNewQuery`. Furthermore, it is recursive, so even if we keep it, the trees will grow indefinitely and will have many redundancies.

**Comment by izlatkin** [comment]
[seq_calls_wo_adt.smt2.txt](https://github.com/izlatkin/solidity_testgen/files/9651206/seq_calls_wo_adt.smt2.txt)
contract_C:^call_1:^call_2:

there are two functions in this contract. For `cur_bnb = 2` it should generate 3 chcs 

```
summary_4_function_call_1__34_63_0 /\ summary_4_function_call_1__34_63_0
summary_6_function_call_2__62_63_0 /\ summary_6_function_call_2__62_63_0
summary_6_function_call_2__62_63_0 /\ summary_4_function_call_1__34_63_0
summary_4_function_call_1__34_63_0 /\ summary_6_function_call_2__62_63_0
```
