### ISSUE TITLE
[encoding] some CHCs have src that are not presented in dst set

### ISSUE THREAD

**Issue by izlatkin** [izlatkin/solidity_testgen#3]
The majority of encoding files have CHCs that have "src" that are not presented in "dst" set

for example, for encoding 
[nested_if_wo_adt.smt2.txt](https://github.com/izlatkin/solidity_testgen/files/8922575/nested_if_wo_adt.smt2.txt)

source file ([here](https://github.com/leonardoalt/cav_2022_artifact/blob/main/regression/control_flow/branches_with_return/nested_if.sol))

Numeric representations of CHC:
```
0 srs:  dst: 67
1 srs:  67 144 dst: 67
2 srs:  dst: 154
3 srs:  154 dst: 169
4 srs:  169 dst: 187
5 srs:  187 dst: 229
6 srs:  187 dst: 236
7 srs:  229 dst: 243
8 srs:  243 dst: 282
9 srs:  243 dst: 288
10 srs:  282 dst: 346
11 srs:  346 dst: 351
12 srs:  282 dst: 393
13 srs:  398 dst: 288
14 srs:  288 dst: 236
15 srs:  236 dst: 414
16 srs:  414 dst: 481
17 srs:  414 dst: 487
18 srs:  481 dst: 526
19 srs:  526 dst: 351
20 srs:  481 dst: 393
21 srs:  564 dst: 569
22 srs:  487 dst: 602
23 srs:  602 dst: 351
24 srs:  487 dst: 393
25 srs:  639 dst: 569
26 srs:  569 dst: 393
27 srs:  393 dst: 351
28 srs:  dst: 658
29 srs:  658 351 dst: 144
30 srs:  778 144 dst: 778
31 srs:  dst: 788
32 srs:  788 dst: 795
33 srs:  795 dst: 802
34 srs:  dst: 810
35 srs:  810 802 dst: 820
36 srs:  810 802 dst: 820
37 srs:  820 dst: 778
38 srs:  778 144 dst: 841
```
src numbers that are NOT dst:
```
98 - 13(index) Expr: <>
564 - 21(index) Expr: block_21_return_ghost_nested_if_43_57_0
639 - 25(index) Expr: 639block_23_return_ghost_nested_if_52_57_0
```

In all smt files, which we used before, CHCs had following structure
src(source) -> distinction(dst) -linear case
or
{src_1, … src_n) -> destination(dst) - nonlinear case
{empty}->destination(dst) - entrance case

So src always used to be a dst somewhere.

**Comment by izlatkin** [comment]
25 srs: (((((((((((((((((((((((((((((((((((((((((((((((((((((((([&&    error_1=error_0    expr_48_1=(!(expr_46_0=expr_47_0))    expr_47_0=2    expr_46_0>=0    expr_46_0<=115792089237316195423570985008687907853269984665640564039457584007913129639935    expr_46_0=a_2_1    _7_2=expr_51_0    expr_51_0=1]&&(error_1=_FH_568))&&(this_0=_FH_569))&&(crypto_0_ecrecover_21=_FH_570))&&(crypto_0_keccak256_22=_FH_571))&&(crypto_0_ripemd160_23=_FH_572))&&(crypto_0_sha256_24=_FH_573))&&(tx_0_block.basefee_3=_FH_574))&&(tx_0_block.chainid_4=_FH_575))&&(tx_0_block.coinbase_5=_FH_576))&&(tx_0_block.difficulty_6=_FH_577))&&(tx_0_block.gaslimit_7=_FH_578))&&(tx_0_block.number_8=_FH_579))&&(tx_0_block.timestamp_9=_FH_580))&&(tx_0_blockhash_10=_FH_581))&&(tx_0_msg.data_11_bytes_tuple_accessor_array_1=_FH_582))&&(tx_0_msg.data_11_bytes_tuple_accessor_length_2=_FH_583))&&(tx_0_msg.sender_12=_FH_584))&&(tx_0_msg.sig_13=_FH_585))&&(tx_0_msg.value_14=_FH_586))&&(tx_0_tx.gasprice_15=_FH_587))&&(tx_0_tx.origin_16=_FH_588))&&(state_0_balances_0=_FH_589))&&(a_2_0=_FH_590))&&(b_4_0=_FH_591))&&(state_1_balances_0=_FH_592))&&(a_2_1=_FH_593))&&(b_4_1=_FH_594))&&(_7_2=_FH_595))&&(error_1=_FH_512'))&&(this_0=_FH_513'))&&(crypto_0_ecrecover_21=_FH_514'))&&(crypto_0_keccak256_22=_FH_515'))&&(crypto_0_ripemd160_23=_FH_516'))&&(crypto_0_sha256_24=_FH_517'))&&(tx_0_block.basefee_3=_FH_518'))&&(tx_0_block.chainid_4=_FH_519'))&&(tx_0_block.coinbase_5=_FH_520'))&&(tx_0_block.difficulty_6=_FH_521'))&&(tx_0_block.gaslimit_7=_FH_522'))&&(tx_0_block.number_8=_FH_523'))&&(tx_0_block.timestamp_9=_FH_524'))&&(tx_0_blockhash_10=_FH_525'))&&(tx_0_msg.data_11_bytes_tuple_accessor_array_1=_FH_526'))&&(tx_0_msg.data_11_bytes_tuple_accessor_length_2=_FH_527'))&&(tx_0_msg.sender_12=_FH_528'))&&(tx_0_msg.sig_13=_FH_529'))&&(tx_0_msg.value_14=_FH_530'))&&(tx_0_tx.gasprice_15=_FH_531'))&&(tx_0_tx.origin_16=_FH_532'))&&(state_0_balances_0=_FH_533'))&&(a_2_0=_FH_534'))&&(b_4_0=_FH_535'))&&(state_1_balances_0=_FH_536'))&&(a_2_1=_FH_537'))&&(b_4_1=_FH_538'))&&(_7_2=_FH_539'))

**Comment by izlatkin** [comment]
`block_21_return_ghost_nested_if_43_57_0` is declared and used
But the set of definitive rules `block_21_return_ghost_nested_if_43_57_0` is empty

**Comment by leonardoalt** [comment]
> `block_21_return_ghost_nested_if_43_57_0` is declared and used But the set of definitive rules `block_21_return_ghost_nested_if_43_57_0` is empty. There is NO "declare-fun"

@izlatkin not sure what you mean here? Or what the specific question is?
